# Generated by Django 2.0.4 on 2018-05-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('F', 'Frasier'), ('N', 'Niles'), ('M', 'Martin'), ('D', 'Daphne'), ('R', 'Roz'), ('E', 'Eddie')], default='F', max_length=1)),
                ('body', models.CharField(blank=True, default='', max_length=255)),
                ('answer', models.CharField(blank=True, default='', max_length=255)),
                ('false_answers', models.IntegerField()),
                ('true_answers', models.IntegerField()),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
