# Generated by Django 2.0.4 on 2018-05-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='false_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='true_answers',
            field=models.IntegerField(default=0),
        ),
    ]
