# Generated by Django 2.0.4 on 2018-07-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_question_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='false_answers',
        ),
        migrations.AddField(
            model_name='question',
            name='total_answers',
            field=models.IntegerField(default=0),
        ),
    ]
